sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        ignore_exceptions:
            - Symfony\Component\Security\Core\Exception\AccessDeniedException
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
when@dev:
    sentry:
        dsn: null
